spring:
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
      image:
        options:
          model: dall-e-3
          response_format: b64_json
      ollama:
        base-url: http://localhost:11434
        chat:
          model: mistral
          options:
            temperature: 0.7
